run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unused
    - gofmt
    - goimports

linters-settings:
  goimports:
    local-prefixes: github.com/Leon180/workingbad

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
