// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: edges.sql

package sqlcdb

import (
	"context"
	"database/sql"
)

const detachEdge = `-- name: DetachEdge :execrows
UPDATE edges SET is_current = 0 WHERE id = ? AND is_current = 1
`

func (q *Queries) DetachEdge(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, detachEdge, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getEdgeByID = `-- name: GetEdgeByID :one
SELECT id, from_id, to_id, relation, is_current, superseded_by, metadata, created_at, occurred_at, ingested_at, actor, reason FROM edges WHERE id = ?
`

func (q *Queries) GetEdgeByID(ctx context.Context, id string) (Edge, error) {
	row := q.db.QueryRowContext(ctx, getEdgeByID, id)
	var i Edge
	err := row.Scan(
		&i.ID,
		&i.FromID,
		&i.ToID,
		&i.Relation,
		&i.IsCurrent,
		&i.SupersededBy,
		&i.Metadata,
		&i.CreatedAt,
		&i.OccurredAt,
		&i.IngestedAt,
		&i.Actor,
		&i.Reason,
	)
	return i, err
}

const getGoalActivitiesByLogicalID = `-- name: GetGoalActivitiesByLogicalID :many
SELECT e.id, e.logical_id, e.type, e.title, e.body, e.source, e.source_ref, e.origin, e.repo_id, e.author, e.status, e.is_current, e.superseded_by, e.metadata, e.created_at, e.updated_at, e.occurred_at, e.ingested_at, e.actor, e.reason, e.source_event_hash, e.version, e.quality_degraded
  FROM entries AS e
  JOIN edges   AS ed ON ed.from_id = e.logical_id AND ed.relation = 'part_of' AND ed.is_current = 1
 WHERE ed.to_id = (SELECT seed.logical_id FROM entries AS seed WHERE seed.id = ?)
   AND e.type = 'activity'
   AND e.is_current = 1
 ORDER BY e.occurred_at ASC, e.ingested_at ASC
`

// Edges key on the node stable id (logical_id == node.id) since migration 0017,
// so the activity joins by its logical_id and the goal is matched directly by
// its logical_id (no goal-version chain join needed).
func (q *Queries) GetGoalActivitiesByLogicalID(ctx context.Context, id string) ([]Entry, error) {
	rows, err := q.db.QueryContext(ctx, getGoalActivitiesByLogicalID, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Entry{}
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.LogicalID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.Source,
			&i.SourceRef,
			&i.Origin,
			&i.RepoID,
			&i.Author,
			&i.Status,
			&i.IsCurrent,
			&i.SupersededBy,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OccurredAt,
			&i.IngestedAt,
			&i.Actor,
			&i.Reason,
			&i.SourceEventHash,
			&i.Version,
			&i.QualityDegraded,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIncomingLiveEdges = `-- name: GetIncomingLiveEdges :many
SELECT id, from_id, relation, metadata, occurred_at FROM edges
 WHERE to_id = ? AND is_current = 1
`

type GetIncomingLiveEdgesRow struct {
	ID         string
	FromID     string
	Relation   string
	Metadata   string
	OccurredAt sql.NullString
}

func (q *Queries) GetIncomingLiveEdges(ctx context.Context, toID string) ([]GetIncomingLiveEdgesRow, error) {
	rows, err := q.db.QueryContext(ctx, getIncomingLiveEdges, toID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetIncomingLiveEdgesRow{}
	for rows.Next() {
		var i GetIncomingLiveEdgesRow
		if err := rows.Scan(
			&i.ID,
			&i.FromID,
			&i.Relation,
			&i.Metadata,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLiveEdgeByTriple = `-- name: GetLiveEdgeByTriple :one
SELECT id FROM edges
 WHERE from_id = ? AND to_id = ? AND relation = ? AND is_current = 1
`

type GetLiveEdgeByTripleParams struct {
	FromID   string
	ToID     string
	Relation string
}

func (q *Queries) GetLiveEdgeByTriple(ctx context.Context, arg GetLiveEdgeByTripleParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getLiveEdgeByTriple, arg.FromID, arg.ToID, arg.Relation)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getOutgoingLiveEdges = `-- name: GetOutgoingLiveEdges :many
SELECT id, to_id, relation, metadata, occurred_at FROM edges
 WHERE from_id = ? AND is_current = 1
`

type GetOutgoingLiveEdgesRow struct {
	ID         string
	ToID       string
	Relation   string
	Metadata   string
	OccurredAt sql.NullString
}

func (q *Queries) GetOutgoingLiveEdges(ctx context.Context, fromID string) ([]GetOutgoingLiveEdgesRow, error) {
	rows, err := q.db.QueryContext(ctx, getOutgoingLiveEdges, fromID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetOutgoingLiveEdgesRow{}
	for rows.Next() {
		var i GetOutgoingLiveEdgesRow
		if err := rows.Scan(
			&i.ID,
			&i.ToID,
			&i.Relation,
			&i.Metadata,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertEdge = `-- name: InsertEdge :exec
INSERT INTO edges
    (id, from_id, to_id, relation, is_current, metadata,
     actor, reason, occurred_at, ingested_at, created_at)
VALUES (?, ?, ?, ?, 1, ?, ?, ?, ?, ?, ?)
`

type InsertEdgeParams struct {
	ID         string
	FromID     string
	ToID       string
	Relation   string
	Metadata   string
	Actor      sql.NullString
	Reason     sql.NullString
	OccurredAt sql.NullString
	IngestedAt sql.NullString
	CreatedAt  string
}

func (q *Queries) InsertEdge(ctx context.Context, arg InsertEdgeParams) error {
	_, err := q.db.ExecContext(ctx, insertEdge,
		arg.ID,
		arg.FromID,
		arg.ToID,
		arg.Relation,
		arg.Metadata,
		arg.Actor,
		arg.Reason,
		arg.OccurredAt,
		arg.IngestedAt,
		arg.CreatedAt,
	)
	return err
}

const supersedeEdge = `-- name: SupersedeEdge :exec
UPDATE edges SET is_current = 0, superseded_by = ? WHERE id = ?
`

type SupersedeEdgeParams struct {
	SupersededBy sql.NullString
	ID           string
}

func (q *Queries) SupersedeEdge(ctx context.Context, arg SupersedeEdgeParams) error {
	_, err := q.db.ExecContext(ctx, supersedeEdge, arg.SupersededBy, arg.ID)
	return err
}
