// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: entries.sql

package sqlcdb

import (
	"context"
	"database/sql"
)

const flipEntrySuperseded = `-- name: FlipEntrySuperseded :exec
UPDATE entries
   SET is_current = 0, superseded_by = ?, updated_at = ?
 WHERE id = ?
`

type FlipEntrySupersededParams struct {
	SupersededBy sql.NullString
	UpdatedAt    string
	ID           string
}

func (q *Queries) FlipEntrySuperseded(ctx context.Context, arg FlipEntrySupersededParams) error {
	_, err := q.db.ExecContext(ctx, flipEntrySuperseded, arg.SupersededBy, arg.UpdatedAt, arg.ID)
	return err
}

const getEntryByID = `-- name: GetEntryByID :one
SELECT id, logical_id, type, title, body, source, source_ref, origin, repo_id, author, status, is_current, superseded_by, metadata, created_at, updated_at, occurred_at, ingested_at, actor, reason, source_event_hash, version, quality_degraded FROM entries WHERE id = ?
`

func (q *Queries) GetEntryByID(ctx context.Context, id string) (Entry, error) {
	row := q.db.QueryRowContext(ctx, getEntryByID, id)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.LogicalID,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.Source,
		&i.SourceRef,
		&i.Origin,
		&i.RepoID,
		&i.Author,
		&i.Status,
		&i.IsCurrent,
		&i.SupersededBy,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OccurredAt,
		&i.IngestedAt,
		&i.Actor,
		&i.Reason,
		&i.SourceEventHash,
		&i.Version,
		&i.QualityDegraded,
	)
	return i, err
}

const getEntryByLogicalIDAndHash = `-- name: GetEntryByLogicalIDAndHash :one
SELECT id FROM entries
 WHERE logical_id = ?
   AND source_event_hash = ?
   AND is_current = 1
 LIMIT 1
`

type GetEntryByLogicalIDAndHashParams struct {
	LogicalID       string
	SourceEventHash sql.NullString
}

// Idempotency lookup: if a fetched event with this (logical_id, hash) is
// already current, the caller should noop. Returns the live entry id.
func (q *Queries) GetEntryByLogicalIDAndHash(ctx context.Context, arg GetEntryByLogicalIDAndHashParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getEntryByLogicalIDAndHash, arg.LogicalID, arg.SourceEventHash)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getEntryTypeAndCurrent = `-- name: GetEntryTypeAndCurrent :one
SELECT type, is_current FROM entries WHERE id = ?
`

type GetEntryTypeAndCurrentRow struct {
	Type      string
	IsCurrent int64
}

func (q *Queries) GetEntryTypeAndCurrent(ctx context.Context, id string) (GetEntryTypeAndCurrentRow, error) {
	row := q.db.QueryRowContext(ctx, getEntryTypeAndCurrent, id)
	var i GetEntryTypeAndCurrentRow
	err := row.Scan(&i.Type, &i.IsCurrent)
	return i, err
}

const getLiveActivityForSegment = `-- name: GetLiveActivityForSegment :one
SELECT id FROM entries
 WHERE type = 'activity' AND source = 'git' AND source_ref = ? AND is_current = 1
 LIMIT 1
`

func (q *Queries) GetLiveActivityForSegment(ctx context.Context, sourceRef sql.NullString) (string, error) {
	row := q.db.QueryRowContext(ctx, getLiveActivityForSegment, sourceRef)
	var id string
	err := row.Scan(&id)
	return id, err
}

const insertEntryRow = `-- name: InsertEntryRow :exec
INSERT INTO entries
    (id, logical_id, type, title, body, source, source_ref, source_event_hash, origin,
     repo_id, author, actor, reason, status, is_current, superseded_by, metadata,
     version, quality_degraded, occurred_at, ingested_at, created_at, updated_at)
VALUES
    (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertEntryRowParams struct {
	ID              string
	LogicalID       string
	Type            string
	Title           string
	Body            string
	Source          string
	SourceRef       sql.NullString
	SourceEventHash sql.NullString
	Origin          string
	RepoID          sql.NullString
	Author          sql.NullString
	Actor           sql.NullString
	Reason          sql.NullString
	Status          sql.NullString
	IsCurrent       int64
	SupersededBy    sql.NullString
	Metadata        string
	Version         sql.NullInt64
	QualityDegraded sql.NullInt64
	OccurredAt      sql.NullString
	IngestedAt      sql.NullString
	CreatedAt       string
	UpdatedAt       string
}

func (q *Queries) InsertEntryRow(ctx context.Context, arg InsertEntryRowParams) error {
	_, err := q.db.ExecContext(ctx, insertEntryRow,
		arg.ID,
		arg.LogicalID,
		arg.Type,
		arg.Title,
		arg.Body,
		arg.Source,
		arg.SourceRef,
		arg.SourceEventHash,
		arg.Origin,
		arg.RepoID,
		arg.Author,
		arg.Actor,
		arg.Reason,
		arg.Status,
		arg.IsCurrent,
		arg.SupersededBy,
		arg.Metadata,
		arg.Version,
		arg.QualityDegraded,
		arg.OccurredAt,
		arg.IngestedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
