// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: entries_fts.sql

package sqlcdb

import (
	"context"
)

const deleteEntryFTS = `-- name: DeleteEntryFTS :exec
DELETE FROM entries_fts WHERE entry_id = ?
`

func (q *Queries) DeleteEntryFTS(ctx context.Context, entryID string) error {
	_, err := q.db.ExecContext(ctx, deleteEntryFTS, entryID)
	return err
}

const insertEntryFTS = `-- name: InsertEntryFTS :exec
INSERT INTO entries_fts (entry_id, title, body) VALUES (?, ?, ?)
`

type InsertEntryFTSParams struct {
	EntryID string
	Title   string
	Body    string
}

func (q *Queries) InsertEntryFTS(ctx context.Context, arg InsertEntryFTSParams) error {
	_, err := q.db.ExecContext(ctx, insertEntryFTS, arg.EntryID, arg.Title, arg.Body)
	return err
}
