// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package sqlcdb

import (
	"database/sql"
)

type Edge struct {
	ID           string
	FromID       string
	ToID         string
	Relation     string
	IsCurrent    int64
	SupersededBy sql.NullString
	Metadata     string
	CreatedAt    string
}

type Entry struct {
	ID           string
	LogicalID    string
	Type         string
	Title        string
	Body         string
	Source       string
	SourceRef    sql.NullString
	Origin       string
	RepoID       sql.NullString
	Author       sql.NullString
	Status       sql.NullString
	IsCurrent    int64
	SupersededBy sql.NullString
	Metadata     string
	CreatedAt    string
	UpdatedAt    string
}

type RawChange struct {
	ChangeID  string
	RepoID    string
	PatchID   sql.NullString
	CreatedAt string
}
