// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: raw.sql

package sqlcdb

import (
	"context"
	"database/sql"
)

const flipPriorSHAOnChange = `-- name: FlipPriorSHAOnChange :exec
UPDATE raw_commits
   SET is_current = 0, superseded_by = ?
 WHERE change_id = ? AND is_current = 1 AND sha != ?
`

type FlipPriorSHAOnChangeParams struct {
	SupersededBy sql.NullString
	ChangeID     string
	Sha          string
}

func (q *Queries) FlipPriorSHAOnChange(ctx context.Context, arg FlipPriorSHAOnChangeParams) error {
	_, err := q.db.ExecContext(ctx, flipPriorSHAOnChange, arg.SupersededBy, arg.ChangeID, arg.Sha)
	return err
}

const getChangeIDByPatch = `-- name: GetChangeIDByPatch :one
SELECT change_id FROM raw_changes WHERE repo_id = ? AND patch_id = ?
`

type GetChangeIDByPatchParams struct {
	RepoID  string
	PatchID sql.NullString
}

func (q *Queries) GetChangeIDByPatch(ctx context.Context, arg GetChangeIDByPatchParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getChangeIDByPatch, arg.RepoID, arg.PatchID)
	var change_id string
	err := row.Scan(&change_id)
	return change_id, err
}

const getChangeIDBySHA = `-- name: GetChangeIDBySHA :one
SELECT change_id FROM raw_commits WHERE sha = ?
`

func (q *Queries) GetChangeIDBySHA(ctx context.Context, sha string) (string, error) {
	row := q.db.QueryRowContext(ctx, getChangeIDBySHA, sha)
	var change_id string
	err := row.Scan(&change_id)
	return change_id, err
}

const getRawChange = `-- name: GetRawChange :one
SELECT change_id, repo_id, patch_id, created_at, ingested_at FROM raw_changes WHERE change_id = ?
`

func (q *Queries) GetRawChange(ctx context.Context, changeID string) (RawChange, error) {
	row := q.db.QueryRowContext(ctx, getRawChange, changeID)
	var i RawChange
	err := row.Scan(
		&i.ChangeID,
		&i.RepoID,
		&i.PatchID,
		&i.CreatedAt,
		&i.IngestedAt,
	)
	return i, err
}

const insertRawChange = `-- name: InsertRawChange :exec
INSERT INTO raw_changes (change_id, repo_id, patch_id, ingested_at, created_at)
VALUES (?, ?, ?, ?, ?)
`

type InsertRawChangeParams struct {
	ChangeID   string
	RepoID     string
	PatchID    sql.NullString
	IngestedAt sql.NullString
	CreatedAt  string
}

func (q *Queries) InsertRawChange(ctx context.Context, arg InsertRawChangeParams) error {
	_, err := q.db.ExecContext(ctx, insertRawChange,
		arg.ChangeID,
		arg.RepoID,
		arg.PatchID,
		arg.IngestedAt,
		arg.CreatedAt,
	)
	return err
}

const insertRawCommit = `-- name: InsertRawCommit :exec
INSERT INTO raw_commits
    (sha, repo_id, change_id, parent_shas, author, author_time, committer, commit_time,
     message, diff, branch_hint, is_current, superseded_by, ingested_at, created_at)
VALUES
    (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertRawCommitParams struct {
	Sha          string
	RepoID       string
	ChangeID     string
	ParentShas   string
	Author       string
	AuthorTime   string
	Committer    string
	CommitTime   string
	Message      string
	Diff         sql.NullString
	BranchHint   sql.NullString
	IsCurrent    int64
	SupersededBy sql.NullString
	IngestedAt   sql.NullString
	CreatedAt    string
}

func (q *Queries) InsertRawCommit(ctx context.Context, arg InsertRawCommitParams) error {
	_, err := q.db.ExecContext(ctx, insertRawCommit,
		arg.Sha,
		arg.RepoID,
		arg.ChangeID,
		arg.ParentShas,
		arg.Author,
		arg.AuthorTime,
		arg.Committer,
		arg.CommitTime,
		arg.Message,
		arg.Diff,
		arg.BranchHint,
		arg.IsCurrent,
		arg.SupersededBy,
		arg.IngestedAt,
		arg.CreatedAt,
	)
	return err
}
