// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: segments.sql

package sqlcdb

import (
	"context"
	"database/sql"
)

const getCurrentChangesForSegment = `-- name: GetCurrentChangesForSegment :many
SELECT rc.change_id, rc.repo_id, rc.patch_id, rc.ingested_at,
       (SELECT MIN(c.author_time)
          FROM raw_commits c
         WHERE c.change_id = rc.change_id AND c.is_current = 1) AS earliest_author_time
  FROM segment_raw sr
  JOIN raw_changes rc ON rc.change_id = sr.change_id
 WHERE sr.segment_id = ?
   AND EXISTS (SELECT 1 FROM raw_commits c WHERE c.change_id = rc.change_id AND c.is_current = 1)
 ORDER BY earliest_author_time ASC
`

type GetCurrentChangesForSegmentRow struct {
	ChangeID           string
	RepoID             string
	PatchID            sql.NullString
	IngestedAt         sql.NullString
	EarliestAuthorTime interface{}
}

// Returns each live change in the segment plus the earliest author_time of
// its current raw_commit(s). Bitemporal materialise reads this to anchor
// the synthesised activity entry's occurred_at to the source event time.
func (q *Queries) GetCurrentChangesForSegment(ctx context.Context, segmentID string) ([]GetCurrentChangesForSegmentRow, error) {
	rows, err := q.db.QueryContext(ctx, getCurrentChangesForSegment, segmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCurrentChangesForSegmentRow{}
	for rows.Next() {
		var i GetCurrentChangesForSegmentRow
		if err := rows.Scan(
			&i.ChangeID,
			&i.RepoID,
			&i.PatchID,
			&i.IngestedAt,
			&i.EarliestAuthorTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSegmentByKey = `-- name: GetSegmentByKey :one
SELECT id, occurred_at_min, occurred_at_max, ingested_at FROM segments
 WHERE repo_id = ? AND source = ? AND source_ref = ?
`

type GetSegmentByKeyParams struct {
	RepoID    string
	Source    string
	SourceRef string
}

type GetSegmentByKeyRow struct {
	ID            string
	OccurredAtMin sql.NullString
	OccurredAtMax sql.NullString
	IngestedAt    sql.NullString
}

func (q *Queries) GetSegmentByKey(ctx context.Context, arg GetSegmentByKeyParams) (GetSegmentByKeyRow, error) {
	row := q.db.QueryRowContext(ctx, getSegmentByKey, arg.RepoID, arg.Source, arg.SourceRef)
	var i GetSegmentByKeyRow
	err := row.Scan(
		&i.ID,
		&i.OccurredAtMin,
		&i.OccurredAtMax,
		&i.IngestedAt,
	)
	return i, err
}

const insertSegment = `-- name: InsertSegment :exec
INSERT INTO segments
    (id, repo_id, source, source_ref, summary_state, anchor_patch_id, metadata,
     occurred_at_min, occurred_at_max, ingested_at, created_at, updated_at)
VALUES
    (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertSegmentParams struct {
	ID            string
	RepoID        string
	Source        string
	SourceRef     string
	SummaryState  string
	AnchorPatchID sql.NullString
	Metadata      string
	OccurredAtMin sql.NullString
	OccurredAtMax sql.NullString
	IngestedAt    sql.NullString
	CreatedAt     string
	UpdatedAt     string
}

func (q *Queries) InsertSegment(ctx context.Context, arg InsertSegmentParams) error {
	_, err := q.db.ExecContext(ctx, insertSegment,
		arg.ID,
		arg.RepoID,
		arg.Source,
		arg.SourceRef,
		arg.SummaryState,
		arg.AnchorPatchID,
		arg.Metadata,
		arg.OccurredAtMin,
		arg.OccurredAtMax,
		arg.IngestedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const linkSegmentRaw = `-- name: LinkSegmentRaw :exec
INSERT OR IGNORE INTO segment_raw (segment_id, change_id) VALUES (?, ?)
`

type LinkSegmentRawParams struct {
	SegmentID string
	ChangeID  string
}

func (q *Queries) LinkSegmentRaw(ctx context.Context, arg LinkSegmentRawParams) error {
	_, err := q.db.ExecContext(ctx, linkSegmentRaw, arg.SegmentID, arg.ChangeID)
	return err
}

const markSegmentMaterialized = `-- name: MarkSegmentMaterialized :exec
UPDATE segments
   SET summary_state = ?, updated_at = ?
 WHERE id = ?
`

type MarkSegmentMaterializedParams struct {
	SummaryState string
	UpdatedAt    string
	ID           string
}

func (q *Queries) MarkSegmentMaterialized(ctx context.Context, arg MarkSegmentMaterializedParams) error {
	_, err := q.db.ExecContext(ctx, markSegmentMaterialized, arg.SummaryState, arg.UpdatedAt, arg.ID)
	return err
}

const setSegmentTimeWindow = `-- name: SetSegmentTimeWindow :exec
UPDATE segments
   SET occurred_at_min = ?,
       occurred_at_max = ?,
       updated_at = ?
 WHERE id = ?
`

type SetSegmentTimeWindowParams struct {
	OccurredAtMin sql.NullString
	OccurredAtMax sql.NullString
	UpdatedAt     string
	ID            string
}

// Caches MIN/MAX(raw_commits.author_time) across the segment's live changes
// onto the segments row. Called during materialise so subsequent at-time
// queries (e.g. "what segments cover 6/8 14:00?") can use the indexed column
// instead of re-aggregating raw_commits every read.
func (q *Queries) SetSegmentTimeWindow(ctx context.Context, arg SetSegmentTimeWindowParams) error {
	_, err := q.db.ExecContext(ctx, setSegmentTimeWindow,
		arg.OccurredAtMin,
		arg.OccurredAtMax,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateSegment = `-- name: UpdateSegment :exec
UPDATE segments
   SET summary_state = ?, anchor_patch_id = ?, metadata = ?,
       occurred_at_min = ?, occurred_at_max = ?, updated_at = ?
 WHERE id = ?
`

type UpdateSegmentParams struct {
	SummaryState  string
	AnchorPatchID sql.NullString
	Metadata      string
	OccurredAtMin sql.NullString
	OccurredAtMax sql.NullString
	UpdatedAt     string
	ID            string
}

func (q *Queries) UpdateSegment(ctx context.Context, arg UpdateSegmentParams) error {
	_, err := q.db.ExecContext(ctx, updateSegment,
		arg.SummaryState,
		arg.AnchorPatchID,
		arg.Metadata,
		arg.OccurredAtMin,
		arg.OccurredAtMax,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
